#!/usr/bin/env php
<?php

/*
 * IN: Base64 encoded string
 * OUT: Decoded string
 */

$in='';
while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
    	fwrite(STDERR, "error reading from stdin");
	    exit(3);
	}
    $in .= $res;
}
# transform Base64URL to Base64
# Undo substitution of URL-unsafe characters
$in = str_replace(array('-', '_'), array('+', '/'), $in);
# Add padding
$in .= str_repeat('=', 3 - (3 + strlen($in)) % 4);
# Decode
$result=base64_decode($in);
if (false===$result)
{
	fwrite(STDERR, "base64_decode failed");
	exit(3);
}

fwrite(STDOUT, $result);

exit(0);
