#!/usr/bin/env php
<?php

/*
Based on https://github.com/Yubico/php-yubico/blob/master/example/Modhex.php

Copyright (c) 2007-2015 Yubico AB
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

    * Neither the name of the Yubico AB nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * IN: Base64 encoded string
 * OUT: ModHex encoded string
 */

$in='';
while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
        fwrite(STDERR, "error reading from stdin");
        exit(3);
    }
    $in .= $res;
}
$result=base64_decode($in);
if (false===$result)
{
    fwrite(STDERR, "base64_decode failed");
    exit(3);
}
$result=encode($result);

fwrite(STDOUT, $result);

exit(0);


// ModHex encodes the string $src
function encode($src) {
    $TRANSKEY = "cbdefghijklnrtuv"; // translation key used to ModHex a string

    $encoded = "";
    $i = 0;
    $srcLen = strlen($src);
    for ($i = 0; $i < $srcLen; $i++) {
        $bin = (ord($src[$i]));
        $encoded .= $TRANSKEY[((int)$bin >> 4) & 0xf];
        $encoded .= $TRANSKEY[ (int)$bin & 0xf];
    }
    return $encoded;
}