#!/usr/bin/env php
<?php

/*
 * IN: String
 * OUT: Base64 encoded string
 */

$in='';
while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
    	fwrite(STDERR, "error reading from stdin");
	    exit(3);
	}
    $in .= $res;
}

# First encode to Base64, then transform to Base64URL
$result=base64_encode($in);
if (false===$result)
{
	fwrite(STDERR, "base64_encode failed");
	exit(3);
}
# Replace + with - and / with _
$result = str_replace(array('+', '/'), array('-', '_'), $result);
# Remove padding
$result = rtrim($result, '=');

fwrite(STDOUT, $result);

exit(0);
