#!/usr/bin/php
<?php

/*
 * IN: String (should be Base64 encoded)
 * OUT: String formatted as PEM CERTIFICATE
 */

$in='';
while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
    	fwrite(STDERR, "error reading from stdin");
	    exit(3);
	}
    $in .= $res;
}

$result="-----BEGIN CERTIFICATE-----\n".chunk_split(str_replace(array("\n","\r", ' ', "\t"),'',$in), 64, "\n")."-----END CERTIFICATE-----\n";

fwrite(STDOUT, $result);

exit(0);
