#!/usr/bin/env bash

# IN: XML
# OUT: XML (reformatted)

# Check is xmllint is available
if ! command -v xmllint &> /dev/null
then
    echo "xmllint could not be found"
    exit 1
fi

xmllint --c14n - | XMLLINT_INDENT=$'\t' xmllint --encode UTF-8 --format -