#!/usr/bin/env bash

# IN: X.509 certificate in PEM format
# OUT: Decoded certificate (using openssl)

# Check if openssl is available
if ! command -v openssl &> /dev/null
then
    echo "openssl could not be found"
    exit 1
fi

openssl x509 -inform PEM -text -fingerprint
