#!/usr/bin/env php
<?php

/*
 * IN: HTTP URL with SAML Request encoded using HTTP-Redirect binding
 * OUT: SAML AuthnRequest XML
 */

$in='';
while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
    	fwrite(STDERR, "error reading from stdin");
	    exit(3);
	}
    $in .= $res;
}

# Cut SAML AuthnRequest from the URL
$startpos=strpos($in, 'SAMLRequest=');
if (FALSE !== $startpos) {
    $in=substr($in, $startpos + 12);
}
$endpos=strpos($in, '&');
if (FALSE !== $endpos) {
    $in=substr($in, 0, $endpos);
}

$result=urldecode($in);
if (false===$result)
{
	fwrite(STDERR, "urldecode failed");
	exit(3);
}
$result=base64_decode($result);
if (false===$result)
{
	fwrite(STDERR, "base64_decode failed");
	exit(3);
}
$result=gzinflate($result);
if (false===$result)
{
	fwrite(STDERR, "gzinflate failed");
	exit(3);
}

fwrite(STDOUT, $result);

exit(0);
