#!/usr/bin/php
<?php

/*
 * IN: string
 * OUT: URL ecoded string
 */

while (!feof(STDIN))
{
    $res = fread(STDIN, 1024);
    if (false === $res)
    {
    	fwrite(STDERR, "error reading from stdin");
	    exit(3);
	}
    $in .= $res;
}
$result=urlencode($in);
if (false===$result)
{
	fwrite(STDERR, "urlencode failed");
	exit(3);
}

fwrite(STDOUT, $result);

exit(0);
